// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"time"

	"github.com/google/uuid"
)

type GenesisServerPasswordForgot struct {
	UserID     int32     `json:"userID"`
	ResetToken uuid.UUID `json:"resetToken"`
	ValidUntil time.Time `json:"validUntil"`
	IsUsed     bool      `json:"isUsed"`
}

type GenesisServerUser struct {
	ID           int32     `json:"id"`
	UserUuid     uuid.UUID `json:"userUuid"`
	PasswordHash string    `json:"passwordHash"`
	PasswordUuid uuid.UUID `json:"passwordUuid"`
	Email        string    `json:"email"`
	FirstName    string    `json:"firstName"`
	CreatedAt    time.Time `json:"createdAt"`
}
