root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/genesis ."
bin = "tmp/genesis"
full_bin = "./tmp/genesis server --verbose"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
