// Code generated by sqlc. DO NOT EDIT.

package queries

import (
	"time"

	"github.com/google/uuid"
)

type GenesisServerPasswordForgot struct {
	UserID     int32
	ResetToken uuid.UUID
	ValidUntil time.Time
	IsUsed     bool
}

type GenesisServerUser struct {
	ID           int32
	UserUuid     uuid.UUID
	PasswordHash string
	PasswordUuid uuid.UUID
	Email        string
	FirstName    string
	CreatedAt    time.Time
}
